Vizija.0.8/TestFinal/Controllers/GlavnaTabelaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.SessionState;
using TestFinal.Models;

namespace TestFinal.Controllers
{
    [SessionState(SessionStateBehavior.Default)]
    public class GlavnaTabelaController :Controller
    {
        static byte[] pom;
        public void InitializeController(RequestContext context)
        {
            base.Initialize(context);
        }
        public GlavnaTabelaController()
        {

            //if (Session["IDUsername"] == null)
            //    RedirectToAction("Login", "Home");

        }
        private Vizija db = new Vizija();

        // GET: GlavnaTabela
        public ActionResult Index()
        {

            if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.RWE))
            {
                return View(db.GlavnaTabelas.ToList());
            }



            return View("ReadIndex",db.GlavnaTabelas.ToList());
        }

        



        // GET: GlavnaTabela/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GlavnaTabela glavnaTabela = db.GlavnaTabelas.Find(id);
            if (glavnaTabela == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole(RoleName.RE))
                return View("ReadDetails", glavnaTabela);






            return View(glavnaTabela);
        }

        // GET: GlavnaTabela/Create


        [Authorize(Roles =RoleName.RWE+ ","+ RoleName.Admin)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: GlavnaTabela/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDPreduzeca,NazivPreduzeca,AdresaRegistracijePreduzeca,Opstina,MaticniBrojPreduzeca,PIB,BrRacuna,WebStranica,Fotografija,Beleska")] GlavnaTabela glavnaTabela,HttpPostedFileBase image1)
        {

            if (ModelState.IsValid)
            {

                if (image1!=null)
                { 
                    
                
                    glavnaTabela.Fotografija = new byte[image1.ContentLength];
                    image1.InputStream.Read(glavnaTabela.Fotografija, 0, image1.ContentLength);

                }


             


                db.GlavnaTabelas.Add(glavnaTabela);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(glavnaTabela);
        }

        // GET: GlavnaTabela/Edit/5
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Edit(int? id)
        {
            


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GlavnaTabela glavnaTabela = db.GlavnaTabelas.Find(id);

            pom = glavnaTabela.Fotografija;

           
            if (glavnaTabela == null)
            {
                return HttpNotFound();
            }
            return View(glavnaTabela);
        }

        // POST: GlavnaTabela/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDPreduzeca,NazivPreduzeca,AdresaRegistracijePreduzeca,Opstina,MaticniBrojPreduzeca,PIB,BrRacuna,WebStranica,Fotografija,Beleska")] GlavnaTabela glavnaTabela, HttpPostedFileBase image1)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (image1 != null)
                    {
                        glavnaTabela.Fotografija = new byte[image1.ContentLength];
                        image1.InputStream.Read(glavnaTabela.Fotografija, 0, image1.ContentLength);
                    }
                    else
                    {
                        glavnaTabela.Fotografija = pom;
                    }


                    db.Entry(glavnaTabela).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("NotFound", "Error");
                }
                return RedirectToAction("Index");
            }
            return View(glavnaTabela);
        }

        // GET: GlavnaTabela/Delete/5
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GlavnaTabela glavnaTabela = db.GlavnaTabelas.Find(id);
            if (glavnaTabela == null)
            {
                return HttpNotFound();
            }
            return View(glavnaTabela);
        }

        // POST: GlavnaTabela/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                GlavnaTabela glavnaTabela = db.GlavnaTabelas.Find(id);
                db.GlavnaTabelas.Remove(glavnaTabela);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("NotFound", "Error");
            }
          
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vizija.0.8/TestFinal/Controllers/KontaktController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestFinal.Models;

namespace TestFinal.Controllers
{
    public class KontaktController : Controller
    {
        private Vizija db = new Vizija();

        
        // GET: Kontakt
        public ActionResult Index(int id)
        {
          
            var kontakts = db.Kontakts.Include(k => k.GlavnaTabela).Where(k=> k.IDPreduzeca == id);
            
            ViewBag.Id = id;
            pom = id;
            
            ViewBag.Pom = db.GlavnaTabelas.Where(k => k.IDPreduzeca == id).Select(k => k.NazivPreduzeca).FirstOrDefault();

            if (User.IsInRole(RoleName.RE))
                return View("ReadIndex", kontakts.ToList());




            return View(kontakts.ToList());
        }

        // GET: Kontakt/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kontakt kontakt = db.Kontakts.Find(id);
            if (kontakt == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole(RoleName.RE))
                return View("ReadDetails", kontakt);



            return View(kontakt);
        }

        // GET: Kontakt/Create
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Create(int id)
        {
            ViewBag.IDPreduzeca = new SelectList(db.GlavnaTabelas, "IDPreduzeca", "NazivPreduzeca");
            ViewBag.Id = id;
            return View();
        }

        // POST: Kontakt/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDOsoba,IDPreduzeca,Ime,Prezime,RadnoMesto")] Kontakt kontakt, int id)
        {
            if (ModelState.IsValid)
            {
                kontakt.IDPreduzeca = id;
                db.Kontakts.Add(kontakt);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = id});
            }

            ViewBag.IDPreduzeca = new SelectList(db.GlavnaTabelas, "IDPreduzeca", "NazivPreduzeca", kontakt.IDPreduzeca);
            return View(kontakt);
        }

        // GET: Kontakt/Edit/5
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kontakt kontakt = db.Kontakts.Find(id);
            if (kontakt == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDPreduzeca = new SelectList(db.GlavnaTabelas, "IDPreduzeca", "NazivPreduzeca", kontakt.IDPreduzeca);
            return View(kontakt);
        }
        static int pom=0;
        // POST: Kontakt/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDOsoba,IDPreduzeca,Ime,Prezime,RadnoMesto")] Kontakt kontakt)
        {
            if (ModelState.IsValid)
            {
                var rez = db.Kontakts.Where(k => k.IDPreduzeca == pom).Select(k => k.IDPreduzeca).FirstOrDefault();
                kontakt.IDPreduzeca = rez;

                db.Entry(kontakt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = kontakt.IDPreduzeca });
            }
            ViewBag.IDPreduzeca = new SelectList(db.GlavnaTabelas, "IDPreduzeca", "NazivPreduzeca", kontakt.IDPreduzeca);
            return View(kontakt);
        }

        // GET: Kontakt/Delete/5
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            Kontakt kontakt = db.Kontakts.Find(id);
            if (kontakt == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = id;
            return View(kontakt);
        }

        // POST: Kontakt/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           
            Kontakt kontakt = db.Kontakts.Find(id);
            try{
                db.Kontakts.Remove(kontakt);
            }
                catch
            {
               return RedirectToAction("NotFound", "Error");
            }
            //if(kontakt==null)
            //    RedirectToAction("NotFound", "Error");
            db.SaveChanges();
            return RedirectToAction("Index", new { id = kontakt.IDPreduzeca });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vizija.0.8/TestFinal/Controllers/KontaktMailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestFinal.Models;

namespace TestFinal.Controllers
{
    public class KontaktMailController :Controller
    {
        private Vizija db = new Vizija();
        static int pom = 0;
        // GET: KontaktMail
        public ActionResult Index(int id)
        {

            pom = id;
            var kontaktss = db.KontaktMails.Include(k => k.Kontakt).Where(k => k.IDOsoba == id);

            ViewBag.Id = db.Kontakts.Where(k => k.IDOsoba == id).Select(k => k.IDPreduzeca).FirstOrDefault();


            ViewBag.ImeOsobe = db.Kontakts.Where(k => k.IDOsoba == id).Select(k => k.Ime).FirstOrDefault();


            ViewBag.PrezimeOsobe = db.Kontakts.Where(k => k.IDOsoba == id).Select(k => k.Prezime).FirstOrDefault();



            if (User.IsInRole(RoleName.RE))
                return View("ReadIndex", kontaktss.ToList());




            return View(kontaktss.ToList());
        }

        // GET: KontaktMail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KontaktMail kontaktMail = db.KontaktMails.Find(id);
            if (kontaktMail == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole(RoleName.RE))
                return View("ReadDetails", kontaktMail);




            return View(kontaktMail);
        }

        // GET: KontaktMail/Create

        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Create(int id)
        {
            ViewBag.IDOsoba = new SelectList(db.Kontakts, "IDOsoba", "Ime");
            ViewBag.Id = db.Kontakts.Where(k => k.IDPreduzeca == id).Select(k => k.IDOsoba).FirstOrDefault();
            return View();
        }

        // POST: KontaktMail/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDMail,IDOsoba,OznakaPosla,Adresa")] KontaktMail kontaktMail)
        {
            if (ModelState.IsValid)
            {
                var rez = db.Kontakts.Where(k => k.IDOsoba == pom).Select(k => k.IDOsoba).First();
                kontaktMail.IDOsoba = rez;
                db.KontaktMails.Add(kontaktMail);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = kontaktMail.IDOsoba });
            }

            ViewBag.IDOsoba = new SelectList(db.Kontakts, "IDOsoba", "Ime", kontaktMail.IDOsoba);
            return View(kontaktMail);
        }

        // GET: KontaktMail/Edit/5

        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KontaktMail kontaktMail = db.KontaktMails.Find(id);
            if (kontaktMail == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDOsoba = new SelectList(db.Kontakts, "IDOsoba", "Ime", kontaktMail.IDOsoba);
           
            return View(kontaktMail);
        }

        // POST: KontaktMail/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDMail,IDOsoba,OznakaPosla,Adresa")] KontaktMail kontaktMail)
        {
            if (ModelState.IsValid)
            {
                var rez = db.Kontakts.Where(k => k.IDOsoba == pom).Select(k => k.IDOsoba).FirstOrDefault();
                kontaktMail.IDOsoba = rez;
                db.Entry(kontaktMail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = kontaktMail.IDOsoba });
            }

            

           ViewBag.IDOsoba = new SelectList(db.Kontakts, "IDOsoba", "Ime", kontaktMail.IDOsoba);
            return View(kontaktMail);
        }

        // GET: KontaktMail/Delete/5

        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KontaktMail kontaktMail = db.KontaktMails.Find(id);
            if (kontaktMail == null)
            {
                return HttpNotFound();
            }
            return View(kontaktMail);
        }

        // POST: KontaktMail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                KontaktMail kontaktMail = db.KontaktMails.Find(id);
                db.KontaktMails.Remove(kontaktMail);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = kontaktMail.IDOsoba });

            }
          catch
            {
                return RedirectToAction("NotFound", "Error");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vizija.0.8/TestFinal/Views/Kontakt/Create.cshtml
@model TestFinal.Models.Kontakt

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Kontakt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.IDPreduzeca, "IDPreduzeca", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IDPreduzeca", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDPreduzeca, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RadnoMesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RadnoMesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RadnoMesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>


    @Html.ActionLink("Back to List", "Index", new { id = ViewBag.Id })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vizija.0.8/TestFinal/Views/Kontakt/Delete.cshtml
@model TestFinal.Models.Kontakt

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kontakt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RadnoMesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RadnoMesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GlavnaTabela.NazivPreduzeca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GlavnaTabela.NazivPreduzeca)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = Model.IDPreduzeca })
        </div>
    }
</div>

Vizija.0.8/TestFinal/Views/Kontakt/Details.cshtml
@model TestFinal.Models.Kontakt

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Kontakt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RadnoMesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RadnoMesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GlavnaTabela.NazivPreduzeca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GlavnaTabela.NazivPreduzeca)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDOsoba }) |
    @Html.ActionLink("Nazad", "Index", new { id = Model.IDPreduzeca }) |
    <a href="javascript:window.print()">Print</a>
</p>

Vizija.0.8/TestFinal/Views/Kontakt/Edit.cshtml
@model TestFinal.Models.Kontakt

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Kontakt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDOsoba)



        @*<div class="form-group">
            @Html.LabelFor(model => model.IDPreduzeca, "IDPreduzeca", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDPreduzeca", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDPreduzeca, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RadnoMesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RadnoMesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RadnoMesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.IDPreduzeca })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vizija.0.8/TestFinal/Views/Kontakt/Index.cshtml
@model IEnumerable<TestFinal.Models.Kontakt>

@{
    ViewBag.Title = "Index";
}

<h2>
    Zaposleni - @ViewBag.Pom
    <span style="font-size: 40%">   @Html.ActionLink("[Dodaj Novog]", "Create", new { id = ViewBag.Id }) </span>
</h2>


<table class="table table-hover table-responsive table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RadnoMesto)
        </th>

        <th>Telefoni</th>

        <th>E-mail</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RadnoMesto)
            </td>
            <td>
                @Html.ActionLink("Izlistaj", "Index", "KontaktTelefons", new { id = item.IDOsoba }, null)
            </td>
            <td>
                @Html.ActionLink("Prikaži", "Index", "KontaktMail", new { id = item.IDOsoba }, null)
            </td>

            <td>
                @Html.ActionLink("Izmeni", "Edit", new { id = item.IDOsoba }) |
                @Html.ActionLink("Detalji", "Details", new { id = item.IDOsoba }) |
                @Html.ActionLink("Izbriši", "Delete", new { id = item.IDOsoba })
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Nazad", "Index", "GlavnaTabela", new { id = ViewBag.Id }, null)
</div>

Vizija.0.8/TestFinal/Views/Kontakt/ReadIndex.cshtml
@model IEnumerable<TestFinal.Models.Kontakt>

@{
    ViewBag.Title = "Index";
}

<h2>
    Zaposleni - @ViewBag.Pom
    
</h2>


<table class="table table-hover table-responsive table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RadnoMesto)
        </th>

        <th>Telefoni</th>

        <th>E-mail</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RadnoMesto)
            </td>
            <td>
                @Html.ActionLink("Izlistaj", "Index", "KontaktTelefons", new { id = item.IDOsoba }, null)
            </td>
            <td>
                @Html.ActionLink("Prikaži", "Index", "KontaktMail", new { id = item.IDOsoba }, null)
            </td>

            <td>
               
                @Html.ActionLink("Detalji", "Details", new { id = item.IDOsoba }) 
               
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Nazad", "Index", "GlavnaTabela", new { id = ViewBag.Id }, null)
</div>