Vizija.0.8/TestFinal/Models/GlavnaTabela.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class GlavnaTabela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GlavnaTabela()
        {
            this.Kontakts = new HashSet<Kontakt>();
        }

     
        public int IDPreduzeca { get; set; }

        [Display(Name = "Naziv preduzeća")]
        [Required(ErrorMessage = "Neophodno popuniti naziv preduzeća.")]
    
        public string NazivPreduzeca { get; set; }
        [Display(Name = "Adresa")]
        [Required(ErrorMessage = "Neophodno popuniti polje za adresu.")]
        public string AdresaRegistracijePreduzeca { get; set; }

        [Display(Name = "Opština")]
        [Required(ErrorMessage = "Neophodno popuniti polje za opštinu.")]
        public string Opstina { get; set; }

        [Display(Name = "Matični broj")]
        [Required(ErrorMessage = "Neophodno popuniti polje za matični broj.")]
        public string MaticniBrojPreduzeca { get; set; }

        [Display(Name = "PIB")]
        [Required(ErrorMessage = "Neophodno popuniti polje za PIB.")]
        public string PIB { get; set; }

        [Display(Name = "Broj računa")]
        [Required(ErrorMessage = "Neophodno popuniti polje za broj računa.")]
        public string BrRacuna { get; set; }

        [Display(Name = "Veb stranica")]
        [Required(ErrorMessage = "Neophodno popuniti polje za veb sajt.")]       
        public string WebStranica { get; set; }


        [Display(Name = "Pečat")]

        public  byte[] Fotografija { get; set; }


        
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "Beleška")]
        [Required(ErrorMessage = "Neophodno popuniti polje za belešku.")]
        public string Beleska { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontakt> Kontakts { get; set; }
    }
}

Vizija.0.8/TestFinal/Controllers/GlavnaTabelaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.SessionState;
using TestFinal.Models;

namespace TestFinal.Controllers
{
    [SessionState(SessionStateBehavior.Default)]
    public class GlavnaTabelaController :Controller
    {
        static byte[] pom;
        public void InitializeController(RequestContext context)
        {
            base.Initialize(context);
        }
        public GlavnaTabelaController()
        {

            //if (Session["IDUsername"] == null)
            //    RedirectToAction("Login", "Home");

        }
        private Vizija db = new Vizija();

        // GET: GlavnaTabela
        public ActionResult Index()
        {

            if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.RWE))
            {
                return View(db.GlavnaTabelas.ToList());
            }



            return View("ReadIndex",db.GlavnaTabelas.ToList());
        }

        



        // GET: GlavnaTabela/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GlavnaTabela glavnaTabela = db.GlavnaTabelas.Find(id);
            if (glavnaTabela == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole(RoleName.RE))
                return View("ReadDetails", glavnaTabela);






            return View(glavnaTabela);
        }

        // GET: GlavnaTabela/Create


        [Authorize(Roles =RoleName.RWE+ ","+ RoleName.Admin)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: GlavnaTabela/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDPreduzeca,NazivPreduzeca,AdresaRegistracijePreduzeca,Opstina,MaticniBrojPreduzeca,PIB,BrRacuna,WebStranica,Fotografija,Beleska")] GlavnaTabela glavnaTabela,HttpPostedFileBase image1)
        {

            if (ModelState.IsValid)
            {

                if (image1!=null)
                { 
                    
                
                    glavnaTabela.Fotografija = new byte[image1.ContentLength];
                    image1.InputStream.Read(glavnaTabela.Fotografija, 0, image1.ContentLength);

                }


             


                db.GlavnaTabelas.Add(glavnaTabela);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(glavnaTabela);
        }

        // GET: GlavnaTabela/Edit/5
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Edit(int? id)
        {
            


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GlavnaTabela glavnaTabela = db.GlavnaTabelas.Find(id);

            pom = glavnaTabela.Fotografija;

           
            if (glavnaTabela == null)
            {
                return HttpNotFound();
            }
            return View(glavnaTabela);
        }

        // POST: GlavnaTabela/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDPreduzeca,NazivPreduzeca,AdresaRegistracijePreduzeca,Opstina,MaticniBrojPreduzeca,PIB,BrRacuna,WebStranica,Fotografija,Beleska")] GlavnaTabela glavnaTabela, HttpPostedFileBase image1)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (image1 != null)
                    {
                        glavnaTabela.Fotografija = new byte[image1.ContentLength];
                        image1.InputStream.Read(glavnaTabela.Fotografija, 0, image1.ContentLength);
                    }
                    else
                    {
                        glavnaTabela.Fotografija = pom;
                    }


                    db.Entry(glavnaTabela).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("NotFound", "Error");
                }
                return RedirectToAction("Index");
            }
            return View(glavnaTabela);
        }

        // GET: GlavnaTabela/Delete/5
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GlavnaTabela glavnaTabela = db.GlavnaTabelas.Find(id);
            if (glavnaTabela == null)
            {
                return HttpNotFound();
            }
            return View(glavnaTabela);
        }

        // POST: GlavnaTabela/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                GlavnaTabela glavnaTabela = db.GlavnaTabelas.Find(id);
                db.GlavnaTabelas.Remove(glavnaTabela);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("NotFound", "Error");
            }
          
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vizija.0.8/TestFinal/Controllers/KontaktController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestFinal.Models;

namespace TestFinal.Controllers
{
    public class KontaktController : Controller
    {
        private Vizija db = new Vizija();

        
        // GET: Kontakt
        public ActionResult Index(int id)
        {
          
            var kontakts = db.Kontakts.Include(k => k.GlavnaTabela).Where(k=> k.IDPreduzeca == id);
            
            ViewBag.Id = id;
            pom = id;
            
            ViewBag.Pom = db.GlavnaTabelas.Where(k => k.IDPreduzeca == id).Select(k => k.NazivPreduzeca).FirstOrDefault();

            if (User.IsInRole(RoleName.RE))
                return View("ReadIndex", kontakts.ToList());




            return View(kontakts.ToList());
        }

        // GET: Kontakt/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kontakt kontakt = db.Kontakts.Find(id);
            if (kontakt == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole(RoleName.RE))
                return View("ReadDetails", kontakt);



            return View(kontakt);
        }

        // GET: Kontakt/Create
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Create(int id)
        {
            ViewBag.IDPreduzeca = new SelectList(db.GlavnaTabelas, "IDPreduzeca", "NazivPreduzeca");
            ViewBag.Id = id;
            return View();
        }

        // POST: Kontakt/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDOsoba,IDPreduzeca,Ime,Prezime,RadnoMesto")] Kontakt kontakt, int id)
        {
            if (ModelState.IsValid)
            {
                kontakt.IDPreduzeca = id;
                db.Kontakts.Add(kontakt);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = id});
            }

            ViewBag.IDPreduzeca = new SelectList(db.GlavnaTabelas, "IDPreduzeca", "NazivPreduzeca", kontakt.IDPreduzeca);
            return View(kontakt);
        }

        // GET: Kontakt/Edit/5
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kontakt kontakt = db.Kontakts.Find(id);
            if (kontakt == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDPreduzeca = new SelectList(db.GlavnaTabelas, "IDPreduzeca", "NazivPreduzeca", kontakt.IDPreduzeca);
            return View(kontakt);
        }
        static int pom=0;
        // POST: Kontakt/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDOsoba,IDPreduzeca,Ime,Prezime,RadnoMesto")] Kontakt kontakt)
        {
            if (ModelState.IsValid)
            {
                var rez = db.Kontakts.Where(k => k.IDPreduzeca == pom).Select(k => k.IDPreduzeca).FirstOrDefault();
                kontakt.IDPreduzeca = rez;

                db.Entry(kontakt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = kontakt.IDPreduzeca });
            }
            ViewBag.IDPreduzeca = new SelectList(db.GlavnaTabelas, "IDPreduzeca", "NazivPreduzeca", kontakt.IDPreduzeca);
            return View(kontakt);
        }

        // GET: Kontakt/Delete/5
        [Authorize(Roles = RoleName.RWE + "," + RoleName.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            Kontakt kontakt = db.Kontakts.Find(id);
            if (kontakt == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = id;
            return View(kontakt);
        }

        // POST: Kontakt/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           
            Kontakt kontakt = db.Kontakts.Find(id);
            try{
                db.Kontakts.Remove(kontakt);
            }
                catch
            {
               return RedirectToAction("NotFound", "Error");
            }
            //if(kontakt==null)
            //    RedirectToAction("NotFound", "Error");
            db.SaveChanges();
            return RedirectToAction("Index", new { id = kontakt.IDPreduzeca });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vizija.0.8/TestFinal/Views/GlavnaTabela/Create.cshtml
@model TestFinal.Models.GlavnaTabela

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "GlavnaTabela", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GlavnaTabela</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NazivPreduzeca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NazivPreduzeca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NazivPreduzeca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdresaRegistracijePreduzeca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdresaRegistracijePreduzeca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdresaRegistracijePreduzeca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opstina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opstina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opstina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaticniBrojPreduzeca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaticniBrojPreduzeca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaticniBrojPreduzeca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PIB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PIB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PIB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrRacuna, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrRacuna, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrRacuna, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebStranica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebStranica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WebStranica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografija, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
             

                <input type="file" id="image1" name="image1"/>



            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Beleska, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Beleska, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Beleska, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vizija.0.8/TestFinal/Views/GlavnaTabela/Edit.cshtml
@model TestFinal.Models.GlavnaTabela

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "GlavnaTabela", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GlavnaTabela</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDPreduzeca)

        <div class="form-group">
            @Html.LabelFor(model => model.NazivPreduzeca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NazivPreduzeca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NazivPreduzeca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdresaRegistracijePreduzeca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdresaRegistracijePreduzeca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdresaRegistracijePreduzeca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opstina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opstina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opstina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaticniBrojPreduzeca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaticniBrojPreduzeca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaticniBrojPreduzeca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PIB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PIB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PIB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrRacuna, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrRacuna, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrRacuna, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebStranica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebStranica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WebStranica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p></p>
            @Html.LabelFor(model => model.Fotografija, htmlAttributes: new { @class = "control-label col-md-2" })
            <p></p>
            <div class="col-md-10">

                <input type="file" id="image1" name="image1" />
                <p></p>
                @{
        if (Model.Fotografija != null)
        {
            var base64 = Convert.ToBase64String(Model.Fotografija);
            var imgSrc = string.Format("data: image/gif; base64, {0}", base64);
            <img src='@imgSrc' style="max-width:30%; max-height:30%" />
}



                }


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Beleska, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Beleska, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Beleska, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vizija.0.8/TestFinal/Views/GlavnaTabela/Index.cshtml
@model IEnumerable<TestFinal.Models.GlavnaTabela>

@{
    ViewBag.Title = "Index";
}

<h2 style="text-align:center"> <b>Preduzeća </b></h2>


<table class="table table-hover table-responsive table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NazivPreduzeca) 
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdresaRegistracijePreduzeca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opstina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaticniBrojPreduzeca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PIB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrRacuna)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WebStranica)
        </th>
        <th>Zaposleni</th>
        <th>
            @Html.DisplayNameFor(model => model.Fotografija)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Beleska)
        </th>
        <th>Opcije</th>

    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <b>  @Html.DisplayFor(modelItem => item.NazivPreduzeca)</b>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AdresaRegistracijePreduzeca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opstina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaticniBrojPreduzeca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PIB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrRacuna)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WebStranica)
        </td>


        <td>

            @Html.ActionLink("Otvori Listu", "Index","Kontakt", new { id = item.IDPreduzeca }, null)

        </td>



        <td>
            @{ 
                if (item.Fotografija != null)
                {
                    var base64 = Convert.ToBase64String(item.Fotografija);
                    var imgSrc = string.Format("data: image/gif; base64, {0}", base64);
                     <img src='@imgSrc' style="max-width:80px; max-height:80px"/>
                }

               

            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Beleska)
        </td>

        <td>
            @Html.ActionLink("Izmeni", "Edit", new { id=item.IDPreduzeca })
            @Html.ActionLink("Detalji", "Details", new { id=item.IDPreduzeca })
            @Html.ActionLink("Izbriši", "Delete", new { id=item.IDPreduzeca })
        </td>
    </tr>
}

</table>



    


    <div style="text-align:center">
        @Html.ActionLink("[Kreiraj Novo Preduzeće]", "Create")

    </div>